version: '3.4'

services:

  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    hostname: mongo

  app:
    build: .
    volumes:
      - .:/home/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    hostname: app

volumes:
  mongo:
